const Employees = [
  {
    id: 1,
    surname: "Alfredo",
    firstname: "Schwander",
    department: "Security",
    created_on: "18-12-2022",
    ACTION: "Manage",
    attendence: "absent",
    fullName: "Alfredo Schwander",
  },
  {
    id: 2,
    surname: "Kylynn",
    firstname: "Lynas",
    department: "Teaching",
    created_on: "10-06-2022",
    ACTION: "Manage",
    attendence: "present",
    fullName: "Kylynn Lynas",
  },
  {
    id: 3,
    surname: "Brigit",
    firstname: "Janos",
    department: "Teaching",
    created_on: "07-12-2022",
    ACTION: "Manage",
    attendence: "present",
    fullName: "Brigit Janos",
  },
  {
    id: 4,
    surname: "Sam",
    firstname: "Cholwell",
    department: "Administration",
    created_on: "30-10-2022",
    ACTION: "Manage",
    attendence: "absent",
    fullName: "Sam Cholwell",
  },
  {
    id: 5,
    surname: "Cy",
    firstname: "Buxcey",
    department: "Teaching",
    created_on: "09-02-2023",
    ACTION: "Manage",
    attendence: "present",
    fullName: "Cy Buxcey",
  },
  {
    id: 6,
    surname: "Meghan",
    firstname: "Ellgood",
    department: "Security",
    created_on: "03-05-2022",
    ACTION: "Manage",
    attendence: "present",
    fullName: "Meghan Ellgood",
  },
  {
    id: 7,
    surname: "Olivette",
    firstname: "Nolot",
    department: "Security",
    created_on: "24-07-2022",
    ACTION: "Manage",
    attendence: "present",
    fullName: "Olivette Nolot",
  },
  {
    id: 8,
    surname: "Maire",
    firstname: "Hasson",
    department: "Security",
    created_on: "03-02-2023",
    ACTION: "Manage",
    attendence: "absent",
    fullName: "Maire Hasson",
  },
  {
    id: 9,
    surname: "Luce",
    firstname: "De Vaux",
    department: "Security",
    created_on: "28-12-2022",
    ACTION: "Manage",
    attendence: "absent",
    fullName: "Luce De Vaux",
  },
  {
    id: 10,
    surname: "Libby",
    firstname: "Gerritzen",
    department: "Teaching",
    created_on: "20-01-2023",
    ACTION: "Manage",
    attendence: "absent",
    fullName: "Libby Gerritzen",
  },
];

export default Employees;
