const Salaries = [
  {
    ID: "1001",
    NAME: "Joshua Hungevu",
    DEPARTMENT: "Teaching",
    AMOUNT: "₦ 100, 000",
    ACTION: "pay",
  },
  {
    ID: "1002",
    NAME: "Adefarasin Emmanuel",
    DEPARTMENT: "Administration",
    AMOUNT: "130, 000",
    ACTION: "pay",
  },
  {
    ID: "1003",
    NAME: "Travolta John",
    DEPARTMENT: "Security",
    AMOUNT: "₦ 200, 000",
    ACTION: "pay",
  },
  {
    ID: "1004",
    NAME: "Mckein Cynthia",
    DEPARTMENT: "Administration",
    AMOUNT: "₦ 300, 000",
    ACTION: "pay",
  },
  {
    ID: "1005",
    NAME: "Travolta John",
    DEPARTMENT: "Teaching",
    AMOUNT: "₦ 400, 000",
    ACTION: "pay",
  },
  {
    ID: "1006",
    NAME: "Rush Lillian",
    DEPARTMENT: "Administration",
    AMOUNT: "₦ 500, 000",
    ACTION: "pay",
  },
  {
    ID: "1007",
    NAME: "Samantha Agboluade",
    DEPARTMENT: "Administration",
    AMOUNT: "₦ 600, 000",
    ACTION: "pay",
  },
  {
    ID: "1008",
    NAME: "Michael Blank",
    DEPARTMENT: "Security",
    AMOUNT: "₦ 700, 000",
    ACTION: "pay",
  },
  {
    ID: "1009",
    NAME: "Travis Abdullahi",
    DEPARTMENT: "Teaching",
    AMOUNT: "₦ 800, 000",
    ACTION: "pay",
  },
  {
    ID: "1010",
    NAME: "Travolta John",
    DEPARTMENT: "Administration",
    AMOUNT: "₦ 900, 000",
    ACTION: "pay",
  },
];
export default Salaries;
